/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chat */
        get: operations["chat_chat_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** AnswerMessage */
        AnswerMessage: {
            /**
             * Type
             * @constant
             */
            type: "answer";
            /** Answer */
            answer: string;
            /**
             * Citations
             * @default null
             */
            citations: components["schemas"]["Page"][] | null;
        };
        /**
         * ChatDoneEnvelope
         * @description Server-sent event dispatched when streaming is finished.
         */
        ChatDoneEnvelope: {
            /**
             * Event
             * @constant
             */
            event: "end";
            data: components["schemas"]["ChatDonePayload"];
        };
        /**
         * ChatDonePayload
         * @description Payload emitted when the stream has completed successfully.
         */
        ChatDonePayload: {
            /**
             * Message
             * @constant
             */
            message: "[DONE]";
        };
        /**
         * ChatErrorEnvelope
         * @description Server-sent event dispatched when an unrecoverable error occurs.
         */
        ChatErrorEnvelope: {
            /**
             * Event
             * @constant
             */
            event: "error";
            data: components["schemas"]["ChatErrorPayload"];
        };
        /**
         * ChatErrorPayload
         * @description Error payload sent when the stream encounters an exception.
         */
        ChatErrorPayload: {
            /** Error */
            error: string;
        };
        /**
         * ChatStreamEnvelope
         * @description Primary chat event wrapping a streamed message payload.
         */
        ChatStreamEnvelope: {
            /**
             * Event
             * @constant
             */
            event: "message";
            /** Data */
            data: components["schemas"]["TurnStartMessage"] | components["schemas"]["StepStartMessage"] | components["schemas"]["StepStatusMessage"] | components["schemas"]["StepEndMessage"] | components["schemas"]["StepFetchStartMessage"] | components["schemas"]["StepFetchEndMessage"] | components["schemas"]["StepAnswerStartMessage"] | components["schemas"]["StepAnswerDeltaMessage"] | components["schemas"]["StepAnswerEndMessage"] | components["schemas"]["AnswerMessage"];
        };
        /**
         * Page
         * @description Normalized representation of a fetched page.
         */
        Page: {
            /** Url */
            url: string;
            /**
             * Title
             * @default null
             */
            title: string | null;
            /**
             * Snippet
             * @default null
             */
            snippet: string | null;
            /**
             * Favicon
             * @default null
             */
            favicon: string | null;
        };
        /** StepAnswerDeltaMessage */
        StepAnswerDeltaMessage: {
            /**
             * Type
             * @constant
             */
            type: "step.answer.delta";
            /** Title */
            title: string;
            /** Delta */
            delta: string;
        };
        /** StepAnswerEndMessage */
        StepAnswerEndMessage: {
            /**
             * Type
             * @constant
             */
            type: "step.answer.end";
            /** Title */
            title: string;
        };
        /** StepAnswerStartMessage */
        StepAnswerStartMessage: {
            /**
             * Type
             * @constant
             */
            type: "step.answer.start";
            /** Title */
            title: string;
            /**
             * Description
             * @default null
             */
            description: string | null;
        };
        /** StepEndMessage */
        StepEndMessage: {
            /**
             * Type
             * @constant
             */
            type: "step.end";
            /** Title */
            title: string;
            /**
             * Description
             * @default null
             */
            description: string | null;
        };
        /** StepFetchEndMessage */
        StepFetchEndMessage: {
            /**
             * Type
             * @constant
             */
            type: "step.fetch.end";
            /** Title */
            title: string;
            /** Pages */
            pages: components["schemas"]["Page"][];
        };
        /** StepFetchStartMessage */
        StepFetchStartMessage: {
            /**
             * Type
             * @constant
             */
            type: "step.fetch.start";
            /** Title */
            title: string;
            /** Pages */
            pages: components["schemas"]["Page"][];
        };
        /** StepStartMessage */
        StepStartMessage: {
            /**
             * Type
             * @constant
             */
            type: "step.start";
            /** Title */
            title: string;
            /** Description */
            description: string;
        };
        /** StepStatusMessage */
        StepStatusMessage: {
            /**
             * Type
             * @constant
             */
            type: "step.status";
            /** Title */
            title: string;
            /** Description */
            description: string;
        };
        /** TurnStartMessage */
        TurnStartMessage: {
            /**
             * Type
             * @constant
             */
            type: "turn.start";
            /** Conversation Id */
            conversation_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    chat_chat_get: {
        parameters: {
            query: {
                user_message: string;
                conversation_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-Sent Events stream containing chat progress updates and final answer. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ChatStreamEnvelope"] | components["schemas"]["ChatErrorEnvelope"] | components["schemas"]["ChatDoneEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
